name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy getAccountBalance
        run: |
          cd getAccountBalance
          zip -r function.zip lambda_function.py
          aws lambda update-function-code --function-name getAccountBalance --zip-file fileb://function.zip

      - name: Deploy blockCard
        run: |
          cd blockCard
          zip -r function.zip lambda_function.py
          aws lambda update-function-code --function-name blockCard --zip-file fileb://function.zip

      - name: Deploy getFAQ
        run: |
          cd getFAQ
          zip -r function.zip lambda_function.py
          aws lambda update-function-code --function-name getFAQ --zip-file fileb://function.zip
